Update bootstrap-custom-menu-widget.php to make it compatible with PHP 8.x
Because without it provokes PHP Fatal Error:
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /var/www/mycoolsite.io/wp-includes/class-wp-widget-factory.php on line 77 and at least 2 expected in /var/www/mycoolsite.io/wp-includes/class-wp-widget.php:163
Stack trace:
#0 /var/www/mycoolsite.io/wp-includes/class-wp-widget-factory.php(77): WP_Widget->__construct()
#1 /var/www/mycoolsite.io/wp-includes/widgets.php(123): WP_Widget_Factory->register()#2 /var/www/mycoolsite.io/wp-content/themes/DevDmBootstrap3/devdmbootstrap3/lib/bootstrap-custom-menu-widget.php(8): register_widget()
#3 /var/www/mycoolsite.io/wp-includes/class-wp-hook.php(353): register_bootstrap_custom_menu()
#4 /var/www/mycoolsite.io/wp-includes/class-wp-hook.php(377): WP_Hook->apply_filters()
#5 /var/www/mycoolsite.io/wp-includes/plugin.php(523): WP_Hook->do_action()
#6 /var/www/mycoolsite.io/wp-includes/widgets.php(1886): do_action()
#7 /var/www/mycoolsite.io/wp-includes/class-wp-hook.php(353): wp_widgets_init()
#8 /var/www/mycoolsite.io/wp-includes/class-wp-hook.php(377): WP_Hook->apply_filters()
#9 /var/www/mycoolsite.io/wp-includes/plugin.php(523): WP_Hook->do_action()
#10 /var/www/mycoolsite.io/wp-settings.php(779): do_action()
#11 /var/www/mycoolsite.io/wp-config.php(99): require_once('...')
#12 /var/www/mycoolsite.io/wp-load.php(50): require_once('...')
#13 /var/www/mycoolsite.io/wp-blog-header.php(13): require_once('...')
#14 /var/www/mycoolsite.io/index.php(17): require('...')
#15 {main}
  thrown in /var/www/mycoolsite.io/wp-includes/class-wp-widget.php on line 163